---
- hosts: localhost
  vars:
    root_dir: "{{ playbook_dir }}/../../"
  vars_files:
    - "{{ playbook_dir }}/../vars.yml"
    - "{{ playbook_dir }}/../vars_local.yml"
  tasks:
    - name: Start API Dev Image
      docker_container:
        name: ps2alerts-api
        image: ps2alerts/api:dev
        state: started
        restart: no
        recreate: yes
        restart_policy: "no"
        volumes:
          - "{{ root_dir | realpath }}:/app:rw"
        ports:
          - "1337"
        networks:
          - name: "ps2alerts"
        tty: true
        env:
          NODE_ENV: "development"
          VERSION: "12345"
          BASE_URL: "http://dev.api.ps2alerts.com"
          DB_HOST: "ps2alerts-db"
          DB_PORT: "27017"
          DB_USER: "root"
          DB_PASS: "foobar"
          DB_NAME: "ps2alerts"
          DB_DEBUG: "true"
          CENSUS_SERVICE_ID: "{{ census_service_id }}"
        labels:
          traefik.enable: "true"
          traefik.http.routers.ps2alerts-api.rule: "Host(`dev.api.ps2alerts.com`)"
