---
- hosts: localhost
  vars_files:
    - "{{ playbook_dir }}/../vars.yml"
#    - "{{ playbook_dir }}/../vars_local.yml"
  tasks:
    - name: Start API Dev Image
      docker_container:
        name: ps2alerts-api
        image: ps2alerts/api:dev
        state: started
        restart: no
        recreate: yes
        restart_policy: "no"
        volumes:
          - "{{ root_dir | realpath }}:/app:rw"
        networks:
          - name: "ps2alerts"
        networks_cli_compatible: no
        tty: true
        ports:
          - "3000:3000"
        env:
          NODE_ENV: "development"
          VERSION: "12345"
          HTTP_PORT: "3000"
          BASE_URL: "http://dev.api.ps2alerts.com"
          DB_HOST: "ps2alerts-db"
          DB_PORT: "27017"
          DB_USER: "root"
          DB_PASS: "foobar"
          DB_NAME: "ps2alerts"
          DB_DEBUG: "true"
          MQ_HOST: "ps2alerts-mq"
        labels:
          traefik.enable: "false"
          traefik.frontend.rule: "Host(`dev.api.ps2alerts.com`)"
          traefik.docker.network: "ps2alerts"
          traefik.port: "3000"
