---
- hosts: localhost
  vars_files:
    - "{{ playbook_dir }}/../vars.yml"
#    - "{{ playbook_dir }}/../secrets.yml"
  tasks:
    - name: Install docker
      pip:
        name: docker
        state: present

    - name: Create docker network
      docker_network:
        name: ps2alerts
        state: present

    - name: Build API Base image (grab a snickers)
      docker_image:
        name: ps2alerts/api # local image
        state: present
        source: build
        tag: base
        force_source: yes
        build:
          pull: no
          path: "{{ playbook_dir }}/../base"

    - name: Build API Dev image
      docker_image:
        name: ps2alerts/api
        state: present
        source: build
        tag: dev
        force_source: yes
        build:
          pull: no
          path: "{{ playbook_dir }}"

    - name: Get user's current UID
      command: "id -u {{ ansible_user_id }}"
      register: id

    - name: Run Composer for API
      docker_container:
        name: composer
        image: composer/composer
        volumes:
          - "{{ playbook_dir }}/../../app:/app"
        user: "{{ id.stdout }}:{{ id.stdout }}"
        command: install
        labels:
          traefik.enable: "false"

    - name: Start API Dev Image
      docker_container:
        name: ps2alerts-api
        image: ps2alerts/api:dev
        state: started
        restart: yes
        restart_policy: always
        volumes:
          - "{{ playbook_dir }}/../../app:/var/www/html:rw"
        ports:
          - "80"
          - "443"
        networks:
          - name: "ps2alerts"
        env:
          ENVIRONMENT: "development"
          VERSION: "12345"
          DB_USER: "root"
          DB_PASS: "foobar"
          DB_HOST: "ps2alerts-db"
          DB_NAME: "ps2alertsWS"
          DB_NAME_DATA: "ps2alerts_data"
          DB_NAME_ARCHIVE: "ps2alertsArchive"
          REDIS_ENABLED: "1"
          REDIS_HOST: "ps2alerts-api-redis"
          REDIS_DB: "1"
          BASE_URL: "https://api.dev.ps2alerts.com"
          CENSUS_SERVICE_ID: "{{ census_service_id }}"
        labels:
          traefik.enable: "true"
          traefik.http.routers.ps2alerts-api.rule: "Host(`api.dev.ps2alerts.com`)"
          traefik.http.routers.ps2alerts-api.tls: "true"
          traefik.http.routers.ps2alerts-api.tls.domains[0].main: "api.dev.ps2alerts.com"
