---
- hosts: localhost
  vars:
    root_dir: "{{ playbook_dir }}/../../"
  vars_files:
    - "{{ root_dir }}/vars_local.yml"
  tasks:
    - name: Install docker
      pip:
        name: docker
        state: present

    - name: Create docker network
      docker_network:
        name: ps2alerts
        state: present

    - name: Build API Base image (grab a snickers)
      docker_image:
        name: ps2alerts/api
        state: present
        source: build
        tag: base
        force_source: yes
        build:
          pull: no
          path: "{{ root_dir | realpath }}/provisioning/base"

    - name: Build API Dev image
      docker_image:
        name: ps2alerts/api
        state: present
        source: build
        tag: dev
        force_source: yes
        build:
          pull: no
          path: "{{ playbook_dir }}"

    - name: Get user's current UID
      command: "id -u {{ lookup('ENV', 'USER') }}"
      register: id
      when: id is undefined

      # This step has issues on OSX, not quite sure how to fix it. Gets permission denied within the container.
      # Workaround is to just install npm via brew and npm install, meh.
    - name: Run npm install for API deps
      docker_container:
        name: ps2alerts-api-npm
        image: node:12
        volumes:
          - "{{ root_dir | realpath }}:/app:rw"
        user: "{{ id.stdout }}:{{ id.stdout }}"
        command: "npm install"
        labels:
          traefik.enable: "false"

    - name: Start API Dev Image
      docker_container:
        name: ps2alerts-api
        image: ps2alerts/api:dev
        state: started
        restart: no
        recreate: yes
        restart_policy: "no"
        volumes:
          - "{{ root_dir | realpath }}:/app:rw"
        ports:
          - "1337"
        networks:
          - name: "ps2alerts"
        tty: true
        env:
          NODE_ENV: "development"
          VERSION: "12345"
          BASE_URL: "http://dev.api.ps2alerts.com"
          DB_HOST: "ps2alerts-db"
          DB_PORT: "27017"
          DB_USER: "root"
          DB_PASS: "foobar"
          DB_NAME: "ps2alerts"
          DB_DEBUG: "true"
          CENSUS_SERVICE_ID: "{{ census_service_id }}"
        labels:
          traefik.enable: "true"
          traefik.http.routers.ps2alerts-api.rule: "Host(`dev.api.ps2alerts.com`)"
