---
- hosts: localhost
  tasks:
    - name: Stop Dev container
      docker_container:
        name: ps2alerts-api-dev
        state: stopped

    - name: Stop DB container
      docker_container:
        name: ps2alerts-db
        state: stopped

    - name: Stop Redis container
      docker_container:
        name: ps2alerts-api-redis
        state: stopped