---
- hosts: localhost
  vars:
    - USER: "{{ lookup('env', 'HOME') }}"
    - devdir: "{{ playbook_dir }}/.."
  tasks:
    - name: Import hosts into /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 {{ item }}"
      with_items:
        - dev.api.ps2alerts.com
      become: yes

    - name: Install bash alias for easy dev work
      lineinfile:
        path: "{{ USER }}/.bash_aliases"
        line: "alias {{ item }}"
      with_items:
        - 'ps2alerts-api="{{ devdir | realpath }}/"'
        - 'ps2alerts-api-start="ansible-playbook {{ devdir | realpath }}/provisioning/dev/main.yml"'
        - 'ps2alerts-api-stop="ansible-playbook {{ devdir | realpath }}/provisioning/dev/stop.yml"'
        - 'ps2alerts-api-term="docker exec -it ps2alerts-api bash"'
        - 'ps2alerts-api-deploy-staging="ps2alerts-api && ansible-playbook provisioning/staging/deploy.yml --ask-vault-pass"'
        - 'ps2alerts-api-deploy-production="ps2alerts-api && ansible-playbook provisioning/poroduction/deploy.yml --ask-vault-pass"'